// lib/cloud_backend.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart'; // remove if you don't need DB
import 'firebase_options.dart'; // generated by `flutterfire configure`

class CloudBackend {
  static bool _inited = false;

  /// Call this once at app start (before using Auth/Firestore).
  static Future<void> init() async {
    if (_inited) return;
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    _inited = true;
  }

  // ---------- AUTH (email/password) ----------
  static FirebaseAuth get auth => FirebaseAuth.instance;

  static Stream<User?> authChanges() => auth.authStateChanges();

  static Future<UserCredential> signUp({
    required String email,
    required String password,
  }) =>
      auth.createUserWithEmailAndPassword(email: email, password: password);

  static Future<UserCredential> signIn({
    required String email,
    required String password,
  }) =>
      auth.signInWithEmailAndPassword(email: email, password: password);

  static Future<void> signOut() => auth.signOut();

  static String? currentUid() => auth.currentUser?.uid;

  static Future<void> sendPasswordReset(String email) =>
      auth.sendPasswordResetEmail(email: email);

  // ---------- OPTIONAL: Firestore helpers ----------
  static FirebaseFirestore get db => FirebaseFirestore.instance;

  /// Example: write a simple profile doc: users/{uid}
  static Future<void> upsertProfile({required String displayName}) async {
    final uid = currentUid();
    if (uid == null) throw Exception('Not signed in');
    await db.collection('users').doc(uid).set({
      'displayName': displayName,
      'updatedAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  /// Example: read live profile stream
  static Stream<DocumentSnapshot<Map<String, dynamic>>> profileStream() {
    final uid = currentUid();
    if (uid == null) throw Exception('Not signed in');
    return db.collection('users').doc(uid).snapshots();
  }
}
